*************************************************
* NOME.....: !IMPAR.PRG                         *
* FUNÄéO...: IMPAR()                            *
* AUTOR....: MARCELO LEAL LIMAVERDE CABRAL      *
* SINTAXE..: E_IMPAR(< expr num>)               *
* DESCRIÄéO: VERIFICA SE UM NUMERO ê IMPAR      *
*************************************************

FUNC IMPAR

PARAMETERS VAR1

RETURN ((VAR1%2)#0)

*******************************