*************************************************
* NOME.....: !PAR.PRG                           *
* FUNÄéO...: PAR()                              *
* AUTOR....: MARCELO LEAL LIMAVERDE CABRAL      *
* SINTAXE..: E_PAR(< expr num>)                 *
* DESCRIÄéO: VERIFICA SE UM NUMERO ê PAR        *
*************************************************

FUNC PAR

PARAMETERS VAR1

RETURN ((VAR1%2)=0)

*******************************